#!/usr/bin/env bash

black='#100e23'
white='#cbe3e7'
accent='#aaffe4'
grey='#565575'
bground='#1e1c31'
alert='#ff99e3'
border='#aaffe4'
indicator=$border

~/.scripts/startup.nu &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 \
	a s d f h j k l

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color $accent
bspc config normal_border_color $bground
bspc config split_ratio          0.51
bspc config borderless_monocle true
bspc config single_monocle     true
bspc config directional_focus_tightness    low
bspc config click_to_focus any

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a floatwin state=floating
bspc rule -a corectrl state=floating hidden=on
