require("various-textobjs").setup({ useDefaultKeymaps = false })
map({ "o", "x" }, "ii", "<cmd>lua require('various-textobjs').indentation(true, true)<CR>")
map({ "o", "x" }, "ai", "<cmd>lua require('various-textobjs').indentation(false, true)<CR>")
map({ "o", "x" }, "iI", "<cmd>lua require('various-textobjs').indentation(true, true)<CR>")
map({ "o", "x" }, "aI", "<cmd>lua require('various-textobjs').indentation(false, false)<CR>")
-- map({ "o", "x" }, "YOUR_MAPPING", "<cmd>lua require('various-textobjs').toNextClosingBracket()<CR>")
map({ "o" }, "R", "<cmd>lua require('various-textobjs').restOfParagraph()<CR>")
map({ "o", "x" }, "_", "<cmd>lua require('various-textobjs').lineCharacterwise(true)<CR>")
map({ "o", "x" }, "iv", "<cmd>lua require('various-textobjs').value(true)<CR>")
map({ "o", "x" }, "av", "<cmd>lua require('various-textobjs').value(false)<CR>")
map({ "o", "x" }, "ik", "<cmd>lua require('various-textobjs').key(true)<CR>")
map({ "o", "x" }, "ak", "<cmd>lua require('various-textobjs').key(false)<CR>")
-- map({ "o", "x" }, "YOUR_MAPPING", "<cmd>lua require('various-textobjs').url()<CR>")
map({ "o", "x" }, "YOUR_MAPPING", "<cmd>lua require('various-textobjs').chainMember(true)<CR>")
map({ "o", "x" }, "YOUR_MAPPING", "<cmd>lua require('various-textobjs').chainMember(false)<CR>")
