# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Microsoft.DotNet.ILCompiler"; version = "7.0.5"; sha256 = "0jcn9lzx6jz5vk7da3w3sx7kaq546przk16534jgjsq9k5nnnzpl"; })
]
