#!/usr/bin/env zsh

for window in $(bspc query -N -n .hidden.window)
do
	printf "%s\t%s\n" $window "$(xdotool getwindowname $window)"
done \
	| rofi -dmenu -i -auto-select -p "Show window" \
	| cut -f 1 \
	| read node

[[ -n $node ]] || exit 1
bspc node $node -g hidden=off -t floating
bspc node $node -d any.focused
bspc node -f $node
